Description: >

  This CloudFormation template will deploy a full CI/CD pipeline for Go Lambda serverless application.
  It is inspired by https://github.com/aws-samples/golang-deployment-pipeline.

Parameters:
  GitHubOAuthToken:
    Description: Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
    Type: String
  GitHubUser:
    Description: Enter GitHub username of the repository owner
    Type: String
  GitHubRepository:
    Description: Enter the repository name that should be monitored for changes
    Type: String
  GitHubBranch:
    Description: Enter the GitHub branch to monitored
    Type: String
    Default: master

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Application Configuration
        Parameters:
          - GitHubOAuthToken
          - GitHubUser
          - GitHubRepository
          - GitHubBranch

    ParameterLabels:
      GitHubRepository:
        default: Repository Name
      GitHubUser:
        default: Repository Owner
      GitHubBranch:
        default: Repository Branch
      GitHubOAuthToken:
        default: OAuth2 Token

Resources:
  ArtifactS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref GitHubRepository
      RoleArn: !Sub ${CodePipelineRole.Arn}
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: Source
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: Source
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Built
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 2
        - Name: Deploy
          Actions:
            - Name: create-changeset
              InputArtifacts:
                - Name: Built
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts: []
              Configuration:
                StackName: !Sub ${GitHubRepository}-lambda
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cloudformation-service-role'
                ChangeSetName: pipeline-changeset
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: Built::cloudformation/output-template.yml
              RunOrder: 1
            - Name: execute-changeset
              InputArtifacts: []
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts: []
              Configuration:
                StackName: !Sub ${GitHubRepository}-lambda
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: pipeline-changeset
              RunOrder: 2

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref GitHubRepository
      Description: !Sub Build project for ${GitHubRepository}
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - go get -d -t -v ./...
                - go get -u golang.org/x/lint/golint
            pre_build:
              commands:
                - |
                  for dir in lambdas/*/
                  do
                      dir=${dir%*/}
                      echo Lint and Test: ${dir##*/}
                      in=${PWD}/${dir}

                      golint -set_exit_status ${PWD}/${dir}
                      go test ${in}
                  done
            build:
              commands:
                - |
                  for dir in lambdas/*/
                  do
                      dir=${dir%*/}
                      echo Building: ${dir##*/}
                      in=${PWD}/${dir}

                      go build -o ${in}/main ${in}
                  done
                - aws cloudformation package --template-file cloudformation/template.yml --kms-key-id ${KMS_KEY_ID} --s3-bucket ${ARTIFACT_S3_BUCKET} --output-template-file cloudformation/output-template.yml
          artifacts:
            type: zip
            files:
              - cloudformation/template.yml
              - cloudformation/output-template.yml

      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/golang:1.11
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_S3_BUCKET
            Value: !Sub ${ArtifactS3Bucket}
          - Name: KMS_KEY_ID
            Value: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      Artifacts:
        Name: !Ref GitHubRepository
        Type: CODEPIPELINE

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${GitHubRepository}-codepipeline-${AWS::Region}
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Action": "sts:AssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "Service": "codepipeline.amazonaws.com"
                }
            }]
        }
      Policies:
        - PolicyName: !Sub ${GitHubRepository}-codepipeline-${AWS::Region}
          PolicyDocument: !Sub |
            {
                "Statement": [
                    {
                        "Action": [ "s3:GetBucketVersioning" ],
                        "Resource": [ "arn:aws:s3:::${ArtifactS3Bucket}" ],
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "s3:PutObject",
                            "s3:GetObject",
                            "S3:GetObjectVersion"
                        ],
                        "Resource": [
                            "arn:aws:s3:::${ArtifactS3Bucket}/${GitHubRepository}/*",
                            "arn:aws:s3:::${ArtifactS3Bucket}/*"
                        ],
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "codedeploy:CreateDeployment",
                            "codedeploy:GetApplicationRevision",
                            "codedeploy:GetDeployment",
                            "codedeploy:GetDeploymentConfig",
                            "codedeploy:RegisterApplicationRevision"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "cloudformation:CreateStack",
                            "cloudformation:DeleteStack",
                            "cloudformation:DescribeStacks",
                            "cloudformation:UpdateStack",
                            "cloudformation:CreateChangeSet",
                            "cloudformation:DeleteChangeSet",
                            "cloudformation:DescribeChangeSet",
                            "cloudformation:ExecuteChangeSet",
                            "cloudformation:SetStackPolicy",
                            "cloudformation:ValidateTemplate",
                            "iam:PassRole"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "codebuild:BatchGetBuilds",
                            "codebuild:StartBuild"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    }
                ]
            }

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${GitHubRepository}-codedeploy-${AWS::Region}
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Action": "sts:AssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "Service": "codedeploy.amazonaws.com"
                }
            }]
        }
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-${AWS::Region}
          PolicyDocument: !Sub |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                    "Effect": "Allow",
                    "Action": [
                        "autoscaling:CompleteLifecycleAction",
                        "autoscaling:DeleteLifecycleHook",
                        "autoscaling:DescribeAutoScalingGroups",
                        "autoscaling:DescribeLifecycleHooks",
                        "autoscaling:PutLifecycleHook",
                        "autoscaling:RecordLifecycleActionHeartbeat",
                        "ec2:DescribeInstances",
                        "ec2:DescribeInstanceStatus",
                        "tag:GetTags",
                        "tag:GetResources",
                        "sns:Publish",
                        "cloudwatch:DescribeAlarms"
                    ],
                    "Resource": "*"
                    }
                ]
            }

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${GitHubRepository}-codebuild-${AWS::Region}
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Action": "sts:AssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "Service": "codebuild.amazonaws.com"
                }
            }]
        }
      Policies:
        - PolicyName: !Sub ${GitHubRepository}-codebuild-${AWS::Region}
          PolicyDocument: !Sub |
            {
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Resource": [ "*" ],
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Resource": [
                            "arn:aws:s3:::${ArtifactS3Bucket}/${GitHubRepository}/*",
                            "arn:aws:s3:::${ArtifactS3Bucket}/*"
                        ],
                        "Action": [
                            "s3:GetObject",
                            "s3:GetObjectVersion",
                            "s3:PutObject"
                        ]
                    }
                ]
            }

Outputs:
  CodePipelineURL:
    Description: The URL for the created pipeline
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${GitHubRepository}
  CodeDeployServiceRoleArn:
    Description: The CodeDeploy service role used across all environments
    Value: !GetAtt CodeDeployServiceRole.Arn
    Export:
      Name: !Sub CodeDeployServiceRoleArn-${GitHubRepository}
