AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function that sets log group retention if missing
Parameters:
  RetentionInDays:
    Type: String
    Default: 60
Resources:
  FunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ['lambda.amazonaws.com']
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: '*'
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ../lambdas/log-group-subscription/
      MemorySize: 128
      Description: >-
        Set log retention on Log Groups if missing
      Timeout: 30
      Role: !GetAtt FunctionRole.Arn
      Environment:
        Variables:
          RETENTION_IN_DAYS: !Ref RetentionInDays
      Events:
        ScheduleFunction:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
